import Head from "next/head";
import styles from "@/styles/Home.module.css";
import LoginButton from "@/components/LoginButton";
import SignupButton from "@/components/SignupButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.headerButtons}>
          <LoginButton />
          <SignupButton />
        </div>
      </header>
      <main className={`${styles.main}`}>
        {}
      </main>
    </>
  );
}
